/**
 * This file is autogenerated, do not edit.
 * Run `make` from the scripts directory to produce splash.h
 *
 * Splashes will be stored in PROGMEM (flash).
 * If SSD1306_NO_SPLASH is defined, the splashes are omitted.
 */
